### PR TITLE
Fix request size input range

### LINKED ISSUE #23: `Context` handle invalid number range
https://github.com/dikotl/paal2-lab3/blob/f0bd9f3b2a8bc5969035f214ef66bf4199a2b336/App/Context.cs#L353
```cs
private DynArray<DynArray<T>> RequestMatrixRandom<T>(int rows, Func<T> getRandomItem)
    {
        // TODO: handle invalid number range.
        var maxColumnSize = Request<int>("Input max number of elements") - 1;
        var generated = new DynArray<DynArray<T>>(length: rows);

        for (int row = 0; row < rows; row++)
        {
            generated[row] = Generator.GetRandomDynArray(2..maxColumnSize, getRandomItem);
        }

        return generated;
    }
```

### PR DESCRIPTION
**Pull request by dikotl**

### CODE REVIEW

File: App/Context.cs [hunk 1]
```diff
@@ -17,7 +17,7 @@ public class ExitToMenuException : Exception;
 public class ExitProgramException : Exception;
 
 /// <summary>
-/// Specifies a style for the request message in the Context.Request* methods.
+/// Specifies a style for the request message in the <see cref="Context.Request"/> method.
```
Comment (Remenod) [inline App/Context.cs]: discard this change

File: App/Context.cs [hunk 2]
```diff
@@ -384,4 +383,19 @@ 2. Line by line
...
+    /// Parses <paramref name="input"/> as int and ensures it's positive.
+    /// </summary>
+    /// <param name="input">The user input as a string.</param>
+    /// <returns>A valid array size.</returns>
+    private static int SizeInt(string input)
+    {
+        var size = int.Parse(input);
+
+        if (size < 1)
+            throw new FormatException($"Value {size} is not in valid range (1..∞)");
```
Comment (Remenod) [inline App/Context.cs]: ∞ does not seems right

**Review by Remenod — APPROVED** [review]
